//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibKonfIAI.ApiOrdersServiceUpdate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ApiOrders", ConfigurationName="ApiOrdersServiceUpdate.ApiOrdersPortType")]
    public interface ApiOrdersPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="#update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(productResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(orderResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(productBundleItemType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(productType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(orderType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateResponse")]
        LibKonfIAI.ApiOrdersServiceUpdate.responseType update(LibKonfIAI.ApiOrdersServiceUpdate.requestType updateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="#update", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateResponse")]
        System.Threading.Tasks.Task<LibKonfIAI.ApiOrdersServiceUpdate.responseType> updateAsync(LibKonfIAI.ApiOrdersServiceUpdate.requestType updateRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class requestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenticateType authenticateField;
        
        private paramsType paramsField;
        
        /// <remarks/>
        public authenticateType authenticate {
            get {
                return this.authenticateField;
            }
            set {
                this.authenticateField = value;
                this.RaisePropertyChanged("authenticate");
            }
        }
        
        /// <remarks/>
        public paramsType @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class authenticateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userLoginField;
        
        private string authenticateKeyField;
        
        /// <remarks/>
        public string userLogin {
            get {
                return this.userLoginField;
            }
            set {
                this.userLoginField = value;
                this.RaisePropertyChanged("userLogin");
            }
        }
        
        /// <remarks/>
        public string authenticateKey {
            get {
                return this.authenticateKeyField;
            }
            set {
                this.authenticateKeyField = value;
                this.RaisePropertyChanged("authenticateKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class productResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string sizeIdField;
        
        private string productSizeCodeExternalField;
        
        private int basketPositionField;
        
        private bool basketPositionFieldSpecified;
        
        private int stockIdField;
        
        private bool stockIdFieldSpecified;
        
        private int faultCodeField;
        
        private bool faultCodeFieldSpecified;
        
        private string faultStringField;
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        public string sizeId {
            get {
                return this.sizeIdField;
            }
            set {
                this.sizeIdField = value;
                this.RaisePropertyChanged("sizeId");
            }
        }
        
        /// <remarks/>
        public string productSizeCodeExternal {
            get {
                return this.productSizeCodeExternalField;
            }
            set {
                this.productSizeCodeExternalField = value;
                this.RaisePropertyChanged("productSizeCodeExternal");
            }
        }
        
        /// <remarks/>
        public int basketPosition {
            get {
                return this.basketPositionField;
            }
            set {
                this.basketPositionField = value;
                this.RaisePropertyChanged("basketPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool basketPositionSpecified {
            get {
                return this.basketPositionFieldSpecified;
            }
            set {
                this.basketPositionFieldSpecified = value;
                this.RaisePropertyChanged("basketPositionSpecified");
            }
        }
        
        /// <remarks/>
        public int stockId {
            get {
                return this.stockIdField;
            }
            set {
                this.stockIdField = value;
                this.RaisePropertyChanged("stockId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool stockIdSpecified {
            get {
                return this.stockIdFieldSpecified;
            }
            set {
                this.stockIdFieldSpecified = value;
                this.RaisePropertyChanged("stockIdSpecified");
            }
        }
        
        /// <remarks/>
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool faultCodeSpecified {
            get {
                return this.faultCodeFieldSpecified;
            }
            set {
                this.faultCodeFieldSpecified = value;
                this.RaisePropertyChanged("faultCodeSpecified");
            }
        }
        
        /// <remarks/>
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class orderResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderIdField;
        
        private int orderSerialNumberField;
        
        private string orderStatusField;
        
        private productResultType[] productsResultsField;
        
        private int faultCodeField;
        
        private string faultStringField;
        
        /// <remarks/>
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        public int orderSerialNumber {
            get {
                return this.orderSerialNumberField;
            }
            set {
                this.orderSerialNumberField = value;
                this.RaisePropertyChanged("orderSerialNumber");
            }
        }
        
        /// <remarks/>
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        public productResultType[] productsResults {
            get {
                return this.productsResultsField;
            }
            set {
                this.productsResultsField = value;
                this.RaisePropertyChanged("productsResults");
            }
        }
        
        /// <remarks/>
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class resultsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private orderResultType[] ordersResultsField;
        
        /// <remarks/>
        public orderResultType[] ordersResults {
            get {
                return this.ordersResultsField;
            }
            set {
                this.ordersResultsField = value;
                this.RaisePropertyChanged("ordersResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class errorsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int faultCodeField;
        
        private string faultStringField;
        
        /// <remarks/>
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class responseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private errorsType errorsField;
        
        private resultsType resultsField;
        
        /// <remarks/>
        public errorsType errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        public resultsType results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class productBundleItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string sizeIdField;
        
        private string sizePanelNameField;
        
        private string productIndexField;
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        public string sizeId {
            get {
                return this.sizeIdField;
            }
            set {
                this.sizeIdField = value;
                this.RaisePropertyChanged("sizeId");
            }
        }
        
        /// <remarks/>
        public string sizePanelName {
            get {
                return this.sizePanelNameField;
            }
            set {
                this.sizePanelNameField = value;
                this.RaisePropertyChanged("sizePanelName");
            }
        }
        
        /// <remarks/>
        public string productIndex {
            get {
                return this.productIndexField;
            }
            set {
                this.productIndexField = value;
                this.RaisePropertyChanged("productIndex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class productType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string sizeIdField;
        
        private string productSizeCodeExternalField;
        
        private int basketPositionField;
        
        private bool basketPositionFieldSpecified;
        
        private int stockIdField;
        
        private bool stockIdFieldSpecified;
        
        private bool productFreeField;
        
        private bool productFreeFieldSpecified;
        
        private float productQuantityField;
        
        private bool productQuantityFieldSpecified;
        
        private productQuantityOperationTypeType productQuantityOperationTypeField;
        
        private bool productQuantityOperationTypeFieldSpecified;
        
        private float productRetailPriceField;
        
        private bool productRetailPriceFieldSpecified;
        
        private string remarksToProductField;
        
        private productBundleItemType[] productBundleItemsField;
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        public string sizeId {
            get {
                return this.sizeIdField;
            }
            set {
                this.sizeIdField = value;
                this.RaisePropertyChanged("sizeId");
            }
        }
        
        /// <remarks/>
        public string productSizeCodeExternal {
            get {
                return this.productSizeCodeExternalField;
            }
            set {
                this.productSizeCodeExternalField = value;
                this.RaisePropertyChanged("productSizeCodeExternal");
            }
        }
        
        /// <remarks/>
        public int basketPosition {
            get {
                return this.basketPositionField;
            }
            set {
                this.basketPositionField = value;
                this.RaisePropertyChanged("basketPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool basketPositionSpecified {
            get {
                return this.basketPositionFieldSpecified;
            }
            set {
                this.basketPositionFieldSpecified = value;
                this.RaisePropertyChanged("basketPositionSpecified");
            }
        }
        
        /// <remarks/>
        public int stockId {
            get {
                return this.stockIdField;
            }
            set {
                this.stockIdField = value;
                this.RaisePropertyChanged("stockId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool stockIdSpecified {
            get {
                return this.stockIdFieldSpecified;
            }
            set {
                this.stockIdFieldSpecified = value;
                this.RaisePropertyChanged("stockIdSpecified");
            }
        }
        
        /// <remarks/>
        public bool productFree {
            get {
                return this.productFreeField;
            }
            set {
                this.productFreeField = value;
                this.RaisePropertyChanged("productFree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productFreeSpecified {
            get {
                return this.productFreeFieldSpecified;
            }
            set {
                this.productFreeFieldSpecified = value;
                this.RaisePropertyChanged("productFreeSpecified");
            }
        }
        
        /// <remarks/>
        public float productQuantity {
            get {
                return this.productQuantityField;
            }
            set {
                this.productQuantityField = value;
                this.RaisePropertyChanged("productQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productQuantitySpecified {
            get {
                return this.productQuantityFieldSpecified;
            }
            set {
                this.productQuantityFieldSpecified = value;
                this.RaisePropertyChanged("productQuantitySpecified");
            }
        }
        
        /// <remarks/>
        public productQuantityOperationTypeType productQuantityOperationType {
            get {
                return this.productQuantityOperationTypeField;
            }
            set {
                this.productQuantityOperationTypeField = value;
                this.RaisePropertyChanged("productQuantityOperationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productQuantityOperationTypeSpecified {
            get {
                return this.productQuantityOperationTypeFieldSpecified;
            }
            set {
                this.productQuantityOperationTypeFieldSpecified = value;
                this.RaisePropertyChanged("productQuantityOperationTypeSpecified");
            }
        }
        
        /// <remarks/>
        public float productRetailPrice {
            get {
                return this.productRetailPriceField;
            }
            set {
                this.productRetailPriceField = value;
                this.RaisePropertyChanged("productRetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool productRetailPriceSpecified {
            get {
                return this.productRetailPriceFieldSpecified;
            }
            set {
                this.productRetailPriceFieldSpecified = value;
                this.RaisePropertyChanged("productRetailPriceSpecified");
            }
        }
        
        /// <remarks/>
        public string remarksToProduct {
            get {
                return this.remarksToProductField;
            }
            set {
                this.remarksToProductField = value;
                this.RaisePropertyChanged("remarksToProduct");
            }
        }
        
        /// <remarks/>
        public productBundleItemType[] productBundleItems {
            get {
                return this.productBundleItemsField;
            }
            set {
                this.productBundleItemsField = value;
                this.RaisePropertyChanged("productBundleItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public enum productQuantityOperationTypeType {
        
        /// <remarks/>
        add,
        
        /// <remarks/>
        substract,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class orderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderIdField;
        
        private int orderSerialNumberField;
        
        private bool orderSerialNumberFieldSpecified;
        
        private string orderStatusField;
        
        private apiFlagType apiFlagField;
        
        private bool apiFlagFieldSpecified;
        
        private string apiNoteToOrderField;
        
        private string clientNoteToOrderField;
        
        private string clientNoteToCourierField;
        
        private string orderNoteField;
        
        private productType[] productsField;
        
        private orderPaymentTypeType orderPaymentTypeField;
        
        private bool orderPaymentTypeFieldSpecified;
        
        private bool ignoreBridgeField;
        
        private bool ignoreBridgeFieldSpecified;
        
        private string clientRequestInvoiceField;
        
        private string billingCurrencyField;
        
        private float billingCurrencyRateField;
        
        private bool billingCurrencyRateFieldSpecified;
        
        /// <remarks/>
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        public int orderSerialNumber {
            get {
                return this.orderSerialNumberField;
            }
            set {
                this.orderSerialNumberField = value;
                this.RaisePropertyChanged("orderSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool orderSerialNumberSpecified {
            get {
                return this.orderSerialNumberFieldSpecified;
            }
            set {
                this.orderSerialNumberFieldSpecified = value;
                this.RaisePropertyChanged("orderSerialNumberSpecified");
            }
        }
        
        /// <remarks/>
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        public apiFlagType apiFlag {
            get {
                return this.apiFlagField;
            }
            set {
                this.apiFlagField = value;
                this.RaisePropertyChanged("apiFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool apiFlagSpecified {
            get {
                return this.apiFlagFieldSpecified;
            }
            set {
                this.apiFlagFieldSpecified = value;
                this.RaisePropertyChanged("apiFlagSpecified");
            }
        }
        
        /// <remarks/>
        public string apiNoteToOrder {
            get {
                return this.apiNoteToOrderField;
            }
            set {
                this.apiNoteToOrderField = value;
                this.RaisePropertyChanged("apiNoteToOrder");
            }
        }
        
        /// <remarks/>
        public string clientNoteToOrder {
            get {
                return this.clientNoteToOrderField;
            }
            set {
                this.clientNoteToOrderField = value;
                this.RaisePropertyChanged("clientNoteToOrder");
            }
        }
        
        /// <remarks/>
        public string clientNoteToCourier {
            get {
                return this.clientNoteToCourierField;
            }
            set {
                this.clientNoteToCourierField = value;
                this.RaisePropertyChanged("clientNoteToCourier");
            }
        }
        
        /// <remarks/>
        public string orderNote {
            get {
                return this.orderNoteField;
            }
            set {
                this.orderNoteField = value;
                this.RaisePropertyChanged("orderNote");
            }
        }
        
        /// <remarks/>
        public productType[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        /// <remarks/>
        public orderPaymentTypeType orderPaymentType {
            get {
                return this.orderPaymentTypeField;
            }
            set {
                this.orderPaymentTypeField = value;
                this.RaisePropertyChanged("orderPaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool orderPaymentTypeSpecified {
            get {
                return this.orderPaymentTypeFieldSpecified;
            }
            set {
                this.orderPaymentTypeFieldSpecified = value;
                this.RaisePropertyChanged("orderPaymentTypeSpecified");
            }
        }
        
        /// <remarks/>
        public bool ignoreBridge {
            get {
                return this.ignoreBridgeField;
            }
            set {
                this.ignoreBridgeField = value;
                this.RaisePropertyChanged("ignoreBridge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ignoreBridgeSpecified {
            get {
                return this.ignoreBridgeFieldSpecified;
            }
            set {
                this.ignoreBridgeFieldSpecified = value;
                this.RaisePropertyChanged("ignoreBridgeSpecified");
            }
        }
        
        /// <remarks/>
        public string clientRequestInvoice {
            get {
                return this.clientRequestInvoiceField;
            }
            set {
                this.clientRequestInvoiceField = value;
                this.RaisePropertyChanged("clientRequestInvoice");
            }
        }
        
        /// <remarks/>
        public string billingCurrency {
            get {
                return this.billingCurrencyField;
            }
            set {
                this.billingCurrencyField = value;
                this.RaisePropertyChanged("billingCurrency");
            }
        }
        
        /// <remarks/>
        public float billingCurrencyRate {
            get {
                return this.billingCurrencyRateField;
            }
            set {
                this.billingCurrencyRateField = value;
                this.RaisePropertyChanged("billingCurrencyRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool billingCurrencyRateSpecified {
            get {
                return this.billingCurrencyRateFieldSpecified;
            }
            set {
                this.billingCurrencyRateFieldSpecified = value;
                this.RaisePropertyChanged("billingCurrencyRateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public enum apiFlagType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        registered,
        
        /// <remarks/>
        realized,
        
        /// <remarks/>
        registered_pos,
        
        /// <remarks/>
        realized_pos,
        
        /// <remarks/>
        registration_fault,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public enum orderPaymentTypeType {
        
        /// <remarks/>
        cash_on_delivery,
        
        /// <remarks/>
        prepaid,
        
        /// <remarks/>
        tradecredit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiOrders")]
    public partial class paramsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private orderType[] ordersField;
        
        /// <remarks/>
        public orderType[] orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("orders");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiOrdersPortTypeChannel : LibKonfIAI.ApiOrdersServiceUpdate.ApiOrdersPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiOrdersPortTypeClient : System.ServiceModel.ClientBase<LibKonfIAI.ApiOrdersServiceUpdate.ApiOrdersPortType>, LibKonfIAI.ApiOrdersServiceUpdate.ApiOrdersPortType {
        
        public ApiOrdersPortTypeClient() {
        }
        
        public ApiOrdersPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiOrdersPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiOrdersPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiOrdersPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibKonfIAI.ApiOrdersServiceUpdate.responseType update(LibKonfIAI.ApiOrdersServiceUpdate.requestType updateRequest) {
            return base.Channel.update(updateRequest);
        }
        
        public System.Threading.Tasks.Task<LibKonfIAI.ApiOrdersServiceUpdate.responseType> updateAsync(LibKonfIAI.ApiOrdersServiceUpdate.requestType updateRequest) {
            return base.Channel.updateAsync(updateRequest);
        }
    }
}
