//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibKonfIAI.ApiPaymentsServicesGet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ApiPayments", ConfigurationName="ApiPaymentsServicesGet.ApiPaymentsPortType")]
    public interface ApiPaymentsPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="#get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eventType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponse")]
        LibKonfIAI.ApiPaymentsServicesGet.getResponseType get(LibKonfIAI.ApiPaymentsServicesGet.getRequestType getRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="#get", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponse")]
        System.Threading.Tasks.Task<LibKonfIAI.ApiPaymentsServicesGet.getResponseType> getAsync(LibKonfIAI.ApiPaymentsServicesGet.getRequestType getRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class getRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenticateType authenticateField;
        
        private getParamsType paramsField;
        
        /// <remarks/>
        public authenticateType authenticate {
            get {
                return this.authenticateField;
            }
            set {
                this.authenticateField = value;
                this.RaisePropertyChanged("authenticate");
            }
        }
        
        /// <remarks/>
        public getParamsType @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class authenticateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenticateKeyField;
        
        private string userLoginField;
        
        /// <remarks/>
        public string authenticateKey {
            get {
                return this.authenticateKeyField;
            }
            set {
                this.authenticateKeyField = value;
                this.RaisePropertyChanged("authenticateKey");
            }
        }
        
        /// <remarks/>
        public string userLogin {
            get {
                return this.userLoginField;
            }
            set {
                this.userLoginField = value;
                this.RaisePropertyChanged("userLogin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class eventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string eventCodeField;
        
        private string dateField;
        
        private eventLevelType levelField;
        
        private bool levelFieldSpecified;
        
        private string detailsField;
        
        /// <remarks/>
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        public string eventCode {
            get {
                return this.eventCodeField;
            }
            set {
                this.eventCodeField = value;
                this.RaisePropertyChanged("eventCode");
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        public eventLevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public enum eventLevelType {
        
        /// <remarks/>
        info,
        
        /// <remarks/>
        error,
        
        /// <remarks/>
        warn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class eventLogType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private eventType[] eventLogListField;
        
        /// <remarks/>
        public eventType[] eventLogList {
            get {
                return this.eventLogListField;
            }
            set {
                this.eventLogListField = value;
                this.RaisePropertyChanged("eventLogList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class getResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int orderNumberField;
        
        private bool orderNumberFieldSpecified;
        
        private int ordinalNumberField;
        
        private bool ordinalNumberFieldSpecified;
        
        private float valueField;
        
        private bool valueFieldSpecified;
        
        private string currencyField;
        
        private string accountingDateField;
        
        private paymentStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private int paymentFormIdField;
        
        private bool paymentFormIdFieldSpecified;
        
        private string externalPaymentIdField;
        
        private eventLogType eventLogField;
        
        /// <remarks/>
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool orderNumberSpecified {
            get {
                return this.orderNumberFieldSpecified;
            }
            set {
                this.orderNumberFieldSpecified = value;
                this.RaisePropertyChanged("orderNumberSpecified");
            }
        }
        
        /// <remarks/>
        public int ordinalNumber {
            get {
                return this.ordinalNumberField;
            }
            set {
                this.ordinalNumberField = value;
                this.RaisePropertyChanged("ordinalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ordinalNumberSpecified {
            get {
                return this.ordinalNumberFieldSpecified;
            }
            set {
                this.ordinalNumberFieldSpecified = value;
                this.RaisePropertyChanged("ordinalNumberSpecified");
            }
        }
        
        /// <remarks/>
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        public string accountingDate {
            get {
                return this.accountingDateField;
            }
            set {
                this.accountingDateField = value;
                this.RaisePropertyChanged("accountingDate");
            }
        }
        
        /// <remarks/>
        public paymentStatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        public int paymentFormId {
            get {
                return this.paymentFormIdField;
            }
            set {
                this.paymentFormIdField = value;
                this.RaisePropertyChanged("paymentFormId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool paymentFormIdSpecified {
            get {
                return this.paymentFormIdFieldSpecified;
            }
            set {
                this.paymentFormIdFieldSpecified = value;
                this.RaisePropertyChanged("paymentFormIdSpecified");
            }
        }
        
        /// <remarks/>
        public string externalPaymentId {
            get {
                return this.externalPaymentIdField;
            }
            set {
                this.externalPaymentIdField = value;
                this.RaisePropertyChanged("externalPaymentId");
            }
        }
        
        /// <remarks/>
        public eventLogType eventLog {
            get {
                return this.eventLogField;
            }
            set {
                this.eventLogField = value;
                this.RaisePropertyChanged("eventLog");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public enum paymentStatusType {
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        processed,
        
        /// <remarks/>
        cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class errorsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int faultCodeField;
        
        private bool faultCodeFieldSpecified;
        
        private string faultStringField;
        
        /// <remarks/>
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool faultCodeSpecified {
            get {
                return this.faultCodeFieldSpecified;
            }
            set {
                this.faultCodeFieldSpecified = value;
                this.RaisePropertyChanged("faultCodeSpecified");
            }
        }
        
        /// <remarks/>
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class getResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private errorsType errorsField;
        
        private getResultType resultField;
        
        /// <remarks/>
        public errorsType errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        public getResultType result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public partial class getParamsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentNumberField;
        
        private sourceTypeType sourceTypeField;
        
        /// <remarks/>
        public string paymentNumber {
            get {
                return this.paymentNumberField;
            }
            set {
                this.paymentNumberField = value;
                this.RaisePropertyChanged("paymentNumber");
            }
        }
        
        /// <remarks/>
        public sourceTypeType sourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("sourceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiPayments")]
    public enum sourceTypeType {
        
        /// <remarks/>
        order,
        
        /// <remarks/>
        @return,
        
        /// <remarks/>
        rma,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiPaymentsPortTypeChannel : LibKonfIAI.ApiPaymentsServicesGet.ApiPaymentsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiPaymentsPortTypeClient : System.ServiceModel.ClientBase<LibKonfIAI.ApiPaymentsServicesGet.ApiPaymentsPortType>, LibKonfIAI.ApiPaymentsServicesGet.ApiPaymentsPortType {
        
        public ApiPaymentsPortTypeClient() {
        }
        
        public ApiPaymentsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiPaymentsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiPaymentsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiPaymentsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LibKonfIAI.ApiPaymentsServicesGet.getResponseType get(LibKonfIAI.ApiPaymentsServicesGet.getRequestType getRequest) {
            return base.Channel.get(getRequest);
        }
        
        public System.Threading.Tasks.Task<LibKonfIAI.ApiPaymentsServicesGet.getResponseType> getAsync(LibKonfIAI.ApiPaymentsServicesGet.getRequestType getRequest) {
            return base.Channel.getAsync(getRequest);
        }
    }
}
