//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pakerator.ApiProductsSocksServiceGet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ApiProductsStocks", ConfigurationName="ApiProductsSocksServiceGet.ApiProductsStocksPortType")]
    public interface ApiProductsStocksPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="#get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sizeLocationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(stockLocationsType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(deliveryType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dispositionsSalesType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(dispositionsAuctionsType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSizeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getStockType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getProductResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sizeIdentType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponse")]
        Pakerator.ApiProductsSocksServiceGet.getResponseType get(Pakerator.ApiProductsSocksServiceGet.getRequestType getRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="#get", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponse")]
        System.Threading.Tasks.Task<Pakerator.ApiProductsSocksServiceGet.getResponseType> getAsync(Pakerator.ApiProductsSocksServiceGet.getRequestType getRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenticateType authenticateField;
        
        private getParamsType paramsField;
        
        /// <remarks/>
        public authenticateType authenticate {
            get {
                return this.authenticateField;
            }
            set {
                this.authenticateField = value;
                this.RaisePropertyChanged("authenticate");
            }
        }
        
        /// <remarks/>
        public getParamsType @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class authenticateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string system_keyField;
        
        private string system_loginField;
        
        /// <remarks/>
        public string system_key {
            get {
                return this.system_keyField;
            }
            set {
                this.system_keyField = value;
                this.RaisePropertyChanged("system_key");
            }
        }
        
        /// <remarks/>
        public string system_login {
            get {
                return this.system_loginField;
            }
            set {
                this.system_loginField = value;
                this.RaisePropertyChanged("system_login");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class sizeLocationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string size_idField;
        
        private int location_idField;
        
        private bool location_idFieldSpecified;
        
        private string location_text_idField;
        
        /// <remarks/>
        public string size_id {
            get {
                return this.size_idField;
            }
            set {
                this.size_idField = value;
                this.RaisePropertyChanged("size_id");
            }
        }
        
        /// <remarks/>
        public int location_id {
            get {
                return this.location_idField;
            }
            set {
                this.location_idField = value;
                this.RaisePropertyChanged("location_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool location_idSpecified {
            get {
                return this.location_idFieldSpecified;
            }
            set {
                this.location_idFieldSpecified = value;
                this.RaisePropertyChanged("location_idSpecified");
            }
        }
        
        /// <remarks/>
        public string location_text_id {
            get {
                return this.location_text_idField;
            }
            set {
                this.location_text_idField = value;
                this.RaisePropertyChanged("location_text_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class stockLocationsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stock_idField;
        
        private bool stock_idFieldSpecified;
        
        private sizeLocationType[] sizesField;
        
        /// <remarks/>
        public int stock_id {
            get {
                return this.stock_idField;
            }
            set {
                this.stock_idField = value;
                this.RaisePropertyChanged("stock_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool stock_idSpecified {
            get {
                return this.stock_idFieldSpecified;
            }
            set {
                this.stock_idFieldSpecified = value;
                this.RaisePropertyChanged("stock_idSpecified");
            }
        }
        
        /// <remarks/>
        public sizeLocationType[] sizes {
            get {
                return this.sizesField;
            }
            set {
                this.sizesField = value;
                this.RaisePropertyChanged("sizes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class deliveryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string size_idField;
        
        private string size_nameField;
        
        private float quantityField;
        
        private bool quantityFieldSpecified;
        
        /// <remarks/>
        public string size_id {
            get {
                return this.size_idField;
            }
            set {
                this.size_idField = value;
                this.RaisePropertyChanged("size_id");
            }
        }
        
        /// <remarks/>
        public string size_name {
            get {
                return this.size_nameField;
            }
            set {
                this.size_nameField = value;
                this.RaisePropertyChanged("size_name");
            }
        }
        
        /// <remarks/>
        public float quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class dispositionsSalesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int size_idField;
        
        private bool size_idFieldSpecified;
        
        private string sizeIdField;
        
        private string size_nameField;
        
        private string product_sizecodeField;
        
        private int outsidestockField;
        
        private bool outsidestockFieldSpecified;
        
        private int ownstockField;
        
        private bool ownstockFieldSpecified;
        
        private int allstocksField;
        
        private bool allstocksFieldSpecified;
        
        private int disposition1dField;
        
        private bool disposition1dFieldSpecified;
        
        private int disposition2dField;
        
        private bool disposition2dFieldSpecified;
        
        private int disposition3dField;
        
        private bool disposition3dFieldSpecified;
        
        private int disposition4dField;
        
        private bool disposition4dFieldSpecified;
        
        private int disposition5dField;
        
        private bool disposition5dFieldSpecified;
        
        private int disposition6dField;
        
        private bool disposition6dFieldSpecified;
        
        private int disposition7dField;
        
        private bool disposition7dFieldSpecified;
        
        private int disposition1wField;
        
        private bool disposition1wFieldSpecified;
        
        private int disposition2wField;
        
        private bool disposition2wFieldSpecified;
        
        private int disposition3wField;
        
        private bool disposition3wFieldSpecified;
        
        private int disposition4wField;
        
        private bool disposition4wFieldSpecified;
        
        /// <remarks/>
        public int size_id {
            get {
                return this.size_idField;
            }
            set {
                this.size_idField = value;
                this.RaisePropertyChanged("size_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool size_idSpecified {
            get {
                return this.size_idFieldSpecified;
            }
            set {
                this.size_idFieldSpecified = value;
                this.RaisePropertyChanged("size_idSpecified");
            }
        }
        
        /// <remarks/>
        public string sizeId {
            get {
                return this.sizeIdField;
            }
            set {
                this.sizeIdField = value;
                this.RaisePropertyChanged("sizeId");
            }
        }
        
        /// <remarks/>
        public string size_name {
            get {
                return this.size_nameField;
            }
            set {
                this.size_nameField = value;
                this.RaisePropertyChanged("size_name");
            }
        }
        
        /// <remarks/>
        public string product_sizecode {
            get {
                return this.product_sizecodeField;
            }
            set {
                this.product_sizecodeField = value;
                this.RaisePropertyChanged("product_sizecode");
            }
        }
        
        /// <remarks/>
        public int outsidestock {
            get {
                return this.outsidestockField;
            }
            set {
                this.outsidestockField = value;
                this.RaisePropertyChanged("outsidestock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool outsidestockSpecified {
            get {
                return this.outsidestockFieldSpecified;
            }
            set {
                this.outsidestockFieldSpecified = value;
                this.RaisePropertyChanged("outsidestockSpecified");
            }
        }
        
        /// <remarks/>
        public int ownstock {
            get {
                return this.ownstockField;
            }
            set {
                this.ownstockField = value;
                this.RaisePropertyChanged("ownstock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ownstockSpecified {
            get {
                return this.ownstockFieldSpecified;
            }
            set {
                this.ownstockFieldSpecified = value;
                this.RaisePropertyChanged("ownstockSpecified");
            }
        }
        
        /// <remarks/>
        public int allstocks {
            get {
                return this.allstocksField;
            }
            set {
                this.allstocksField = value;
                this.RaisePropertyChanged("allstocks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool allstocksSpecified {
            get {
                return this.allstocksFieldSpecified;
            }
            set {
                this.allstocksFieldSpecified = value;
                this.RaisePropertyChanged("allstocksSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition1d {
            get {
                return this.disposition1dField;
            }
            set {
                this.disposition1dField = value;
                this.RaisePropertyChanged("disposition1d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition1dSpecified {
            get {
                return this.disposition1dFieldSpecified;
            }
            set {
                this.disposition1dFieldSpecified = value;
                this.RaisePropertyChanged("disposition1dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition2d {
            get {
                return this.disposition2dField;
            }
            set {
                this.disposition2dField = value;
                this.RaisePropertyChanged("disposition2d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition2dSpecified {
            get {
                return this.disposition2dFieldSpecified;
            }
            set {
                this.disposition2dFieldSpecified = value;
                this.RaisePropertyChanged("disposition2dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition3d {
            get {
                return this.disposition3dField;
            }
            set {
                this.disposition3dField = value;
                this.RaisePropertyChanged("disposition3d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition3dSpecified {
            get {
                return this.disposition3dFieldSpecified;
            }
            set {
                this.disposition3dFieldSpecified = value;
                this.RaisePropertyChanged("disposition3dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition4d {
            get {
                return this.disposition4dField;
            }
            set {
                this.disposition4dField = value;
                this.RaisePropertyChanged("disposition4d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition4dSpecified {
            get {
                return this.disposition4dFieldSpecified;
            }
            set {
                this.disposition4dFieldSpecified = value;
                this.RaisePropertyChanged("disposition4dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition5d {
            get {
                return this.disposition5dField;
            }
            set {
                this.disposition5dField = value;
                this.RaisePropertyChanged("disposition5d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition5dSpecified {
            get {
                return this.disposition5dFieldSpecified;
            }
            set {
                this.disposition5dFieldSpecified = value;
                this.RaisePropertyChanged("disposition5dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition6d {
            get {
                return this.disposition6dField;
            }
            set {
                this.disposition6dField = value;
                this.RaisePropertyChanged("disposition6d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition6dSpecified {
            get {
                return this.disposition6dFieldSpecified;
            }
            set {
                this.disposition6dFieldSpecified = value;
                this.RaisePropertyChanged("disposition6dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition7d {
            get {
                return this.disposition7dField;
            }
            set {
                this.disposition7dField = value;
                this.RaisePropertyChanged("disposition7d");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition7dSpecified {
            get {
                return this.disposition7dFieldSpecified;
            }
            set {
                this.disposition7dFieldSpecified = value;
                this.RaisePropertyChanged("disposition7dSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition1w {
            get {
                return this.disposition1wField;
            }
            set {
                this.disposition1wField = value;
                this.RaisePropertyChanged("disposition1w");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition1wSpecified {
            get {
                return this.disposition1wFieldSpecified;
            }
            set {
                this.disposition1wFieldSpecified = value;
                this.RaisePropertyChanged("disposition1wSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition2w {
            get {
                return this.disposition2wField;
            }
            set {
                this.disposition2wField = value;
                this.RaisePropertyChanged("disposition2w");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition2wSpecified {
            get {
                return this.disposition2wFieldSpecified;
            }
            set {
                this.disposition2wFieldSpecified = value;
                this.RaisePropertyChanged("disposition2wSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition3w {
            get {
                return this.disposition3wField;
            }
            set {
                this.disposition3wField = value;
                this.RaisePropertyChanged("disposition3w");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition3wSpecified {
            get {
                return this.disposition3wFieldSpecified;
            }
            set {
                this.disposition3wFieldSpecified = value;
                this.RaisePropertyChanged("disposition3wSpecified");
            }
        }
        
        /// <remarks/>
        public int disposition4w {
            get {
                return this.disposition4wField;
            }
            set {
                this.disposition4wField = value;
                this.RaisePropertyChanged("disposition4w");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool disposition4wSpecified {
            get {
                return this.disposition4wFieldSpecified;
            }
            set {
                this.disposition4wFieldSpecified = value;
                this.RaisePropertyChanged("disposition4wSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class dispositionsAuctionsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int size_idField;
        
        private bool size_idFieldSpecified;
        
        private string sizeIdField;
        
        private string size_nameField;
        
        private string product_sizecodeField;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        /// <remarks/>
        public int size_id {
            get {
                return this.size_idField;
            }
            set {
                this.size_idField = value;
                this.RaisePropertyChanged("size_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool size_idSpecified {
            get {
                return this.size_idFieldSpecified;
            }
            set {
                this.size_idFieldSpecified = value;
                this.RaisePropertyChanged("size_idSpecified");
            }
        }
        
        /// <remarks/>
        public string sizeId {
            get {
                return this.sizeIdField;
            }
            set {
                this.sizeIdField = value;
                this.RaisePropertyChanged("sizeId");
            }
        }
        
        /// <remarks/>
        public string size_name {
            get {
                return this.size_nameField;
            }
            set {
                this.size_nameField = value;
                this.RaisePropertyChanged("size_name");
            }
        }
        
        /// <remarks/>
        public string product_sizecode {
            get {
                return this.product_sizecodeField;
            }
            set {
                this.product_sizecodeField = value;
                this.RaisePropertyChanged("product_sizecode");
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class dispositionsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dispositionsAuctionsType[] auctionsField;
        
        private dispositionsSalesType[] salesField;
        
        /// <remarks/>
        public dispositionsAuctionsType[] auctions {
            get {
                return this.auctionsField;
            }
            set {
                this.auctionsField = value;
                this.RaisePropertyChanged("auctions");
            }
        }
        
        /// <remarks/>
        public dispositionsSalesType[] sales {
            get {
                return this.salesField;
            }
            set {
                this.salesField = value;
                this.RaisePropertyChanged("sales");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class reservationsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float adhocField;
        
        private bool adhocFieldSpecified;
        
        private float auctionField;
        
        private bool auctionFieldSpecified;
        
        private float clientField;
        
        private bool clientFieldSpecified;
        
        private float orderField;
        
        private bool orderFieldSpecified;
        
        private float retailField;
        
        private bool retailFieldSpecified;
        
        private float wholesaleField;
        
        private bool wholesaleFieldSpecified;
        
        /// <remarks/>
        public float adhoc {
            get {
                return this.adhocField;
            }
            set {
                this.adhocField = value;
                this.RaisePropertyChanged("adhoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool adhocSpecified {
            get {
                return this.adhocFieldSpecified;
            }
            set {
                this.adhocFieldSpecified = value;
                this.RaisePropertyChanged("adhocSpecified");
            }
        }
        
        /// <remarks/>
        public float auction {
            get {
                return this.auctionField;
            }
            set {
                this.auctionField = value;
                this.RaisePropertyChanged("auction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool auctionSpecified {
            get {
                return this.auctionFieldSpecified;
            }
            set {
                this.auctionFieldSpecified = value;
                this.RaisePropertyChanged("auctionSpecified");
            }
        }
        
        /// <remarks/>
        public float client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool clientSpecified {
            get {
                return this.clientFieldSpecified;
            }
            set {
                this.clientFieldSpecified = value;
                this.RaisePropertyChanged("clientSpecified");
            }
        }
        
        /// <remarks/>
        public float order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool orderSpecified {
            get {
                return this.orderFieldSpecified;
            }
            set {
                this.orderFieldSpecified = value;
                this.RaisePropertyChanged("orderSpecified");
            }
        }
        
        /// <remarks/>
        public float retail {
            get {
                return this.retailField;
            }
            set {
                this.retailField = value;
                this.RaisePropertyChanged("retail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool retailSpecified {
            get {
                return this.retailFieldSpecified;
            }
            set {
                this.retailFieldSpecified = value;
                this.RaisePropertyChanged("retailSpecified");
            }
        }
        
        /// <remarks/>
        public float wholesale {
            get {
                return this.wholesaleField;
            }
            set {
                this.wholesaleField = value;
                this.RaisePropertyChanged("wholesale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool wholesaleSpecified {
            get {
                return this.wholesaleFieldSpecified;
            }
            set {
                this.wholesaleFieldSpecified = value;
                this.RaisePropertyChanged("wholesaleSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getSizeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string size_idField;
        
        private string size_nameField;
        
        private string product_sizecodeField;
        
        private float quantityField;
        
        private bool quantityFieldSpecified;
        
        private reservationsType reservationsField;
        
        /// <remarks/>
        public string size_id {
            get {
                return this.size_idField;
            }
            set {
                this.size_idField = value;
                this.RaisePropertyChanged("size_id");
            }
        }
        
        /// <remarks/>
        public string size_name {
            get {
                return this.size_nameField;
            }
            set {
                this.size_nameField = value;
                this.RaisePropertyChanged("size_name");
            }
        }
        
        /// <remarks/>
        public string product_sizecode {
            get {
                return this.product_sizecodeField;
            }
            set {
                this.product_sizecodeField = value;
                this.RaisePropertyChanged("product_sizecode");
            }
        }
        
        /// <remarks/>
        public float quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        /// <remarks/>
        public reservationsType reservations {
            get {
                return this.reservationsField;
            }
            set {
                this.reservationsField = value;
                this.RaisePropertyChanged("reservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getStockType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stock_idField;
        
        private bool stock_idFieldSpecified;
        
        private getSizeType[] sizesField;
        
        /// <remarks/>
        public int stock_id {
            get {
                return this.stock_idField;
            }
            set {
                this.stock_idField = value;
                this.RaisePropertyChanged("stock_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool stock_idSpecified {
            get {
                return this.stock_idFieldSpecified;
            }
            set {
                this.stock_idFieldSpecified = value;
                this.RaisePropertyChanged("stock_idSpecified");
            }
        }
        
        /// <remarks/>
        public getSizeType[] sizes {
            get {
                return this.sizesField;
            }
            set {
                this.sizesField = value;
                this.RaisePropertyChanged("sizes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getQuantitiesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getStockType[] stocksField;
        
        private getStockType[] auctionsField;
        
        private getStockType[] orders_unfinishedField;
        
        private dispositionsType dispositionsField;
        
        private deliveryType[] deliveriesField;
        
        private deliveryType[] goods_received_notesField;
        
        private stockLocationsType[] stocks_locationsField;
        
        /// <remarks/>
        public getStockType[] stocks {
            get {
                return this.stocksField;
            }
            set {
                this.stocksField = value;
                this.RaisePropertyChanged("stocks");
            }
        }
        
        /// <remarks/>
        public getStockType[] auctions {
            get {
                return this.auctionsField;
            }
            set {
                this.auctionsField = value;
                this.RaisePropertyChanged("auctions");
            }
        }
        
        /// <remarks/>
        public getStockType[] orders_unfinished {
            get {
                return this.orders_unfinishedField;
            }
            set {
                this.orders_unfinishedField = value;
                this.RaisePropertyChanged("orders_unfinished");
            }
        }
        
        /// <remarks/>
        public dispositionsType dispositions {
            get {
                return this.dispositionsField;
            }
            set {
                this.dispositionsField = value;
                this.RaisePropertyChanged("dispositions");
            }
        }
        
        /// <remarks/>
        public deliveryType[] deliveries {
            get {
                return this.deliveriesField;
            }
            set {
                this.deliveriesField = value;
                this.RaisePropertyChanged("deliveries");
            }
        }
        
        /// <remarks/>
        public deliveryType[] goods_received_notes {
            get {
                return this.goods_received_notesField;
            }
            set {
                this.goods_received_notesField = value;
                this.RaisePropertyChanged("goods_received_notes");
            }
        }
        
        /// <remarks/>
        public stockLocationsType[] stocks_locations {
            get {
                return this.stocks_locationsField;
            }
            set {
                this.stocks_locationsField = value;
                this.RaisePropertyChanged("stocks_locations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class productIdentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private identsType identTypeField;
        
        private string identValueField;
        
        /// <remarks/>
        public identsType identType {
            get {
                return this.identTypeField;
            }
            set {
                this.identTypeField = value;
                this.RaisePropertyChanged("identType");
            }
        }
        
        /// <remarks/>
        public string identValue {
            get {
                return this.identValueField;
            }
            set {
                this.identValueField = value;
                this.RaisePropertyChanged("identValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public enum identsType {
        
        /// <remarks/>
        id,
        
        /// <remarks/>
        index,
        
        /// <remarks/>
        codeExtern,
        
        /// <remarks/>
        codeProducer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getProductResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private productIdentType identField;
        
        private errorsType errorField;
        
        private getQuantitiesType quantitiesField;
        
        /// <remarks/>
        public productIdentType ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
                this.RaisePropertyChanged("ident");
            }
        }
        
        /// <remarks/>
        public errorsType error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        public getQuantitiesType quantities {
            get {
                return this.quantitiesField;
            }
            set {
                this.quantitiesField = value;
                this.RaisePropertyChanged("quantities");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class errorsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int faultCodeField;
        
        private string faultStringField;
        
        /// <remarks/>
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private authenticateType authenticateField;
        
        private errorsType errorsField;
        
        private getProductResponseType[] resultsField;
        
        private bool is_errorsField;
        
        private bool is_errorsFieldSpecified;
        
        /// <remarks/>
        public authenticateType authenticate {
            get {
                return this.authenticateField;
            }
            set {
                this.authenticateField = value;
                this.RaisePropertyChanged("authenticate");
            }
        }
        
        /// <remarks/>
        public errorsType errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        public getProductResponseType[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("results");
            }
        }
        
        /// <remarks/>
        public bool is_errors {
            get {
                return this.is_errorsField;
            }
            set {
                this.is_errorsField = value;
                this.RaisePropertyChanged("is_errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool is_errorsSpecified {
            get {
                return this.is_errorsFieldSpecified;
            }
            set {
                this.is_errorsFieldSpecified = value;
                this.RaisePropertyChanged("is_errorsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class sizeIdentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private identsType identTypeField;
        
        private string identValueField;
        
        /// <remarks/>
        public identsType identType {
            get {
                return this.identTypeField;
            }
            set {
                this.identTypeField = value;
                this.RaisePropertyChanged("identType");
            }
        }
        
        /// <remarks/>
        public string identValue {
            get {
                return this.identValueField;
            }
            set {
                this.identValueField = value;
                this.RaisePropertyChanged("identValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="ApiProductsStocks")]
    public partial class getParamsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sizeIdentType[] productsField;
        
        /// <remarks/>
        public sizeIdentType[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiProductsStocksPortTypeChannel : Pakerator.ApiProductsSocksServiceGet.ApiProductsStocksPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiProductsStocksPortTypeClient : System.ServiceModel.ClientBase<Pakerator.ApiProductsSocksServiceGet.ApiProductsStocksPortType>, Pakerator.ApiProductsSocksServiceGet.ApiProductsStocksPortType {
        
        public ApiProductsStocksPortTypeClient() {
        }
        
        public ApiProductsStocksPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiProductsStocksPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiProductsStocksPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiProductsStocksPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pakerator.ApiProductsSocksServiceGet.getResponseType get(Pakerator.ApiProductsSocksServiceGet.getRequestType getRequest) {
            return base.Channel.get(getRequest);
        }
        
        public System.Threading.Tasks.Task<Pakerator.ApiProductsSocksServiceGet.getResponseType> getAsync(Pakerator.ApiProductsSocksServiceGet.getRequestType getRequest) {
            return base.Channel.getAsync(getRequest);
        }
    }
}
